# Generated by Django 5.2 on 2025-04-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
