# Generated by Django 5.2 on 2025-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_testmodel_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCreatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
